[package]
name = "wren-workflow"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
imara-diff.workspace = true
ls-types.workspace = true
nix.workspace = true
portable-pty.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
vt100.workspace = true
wren-position = { version = "0.1.0", path = "../wren-position" }
wren-types = { version = "0.1.0", path = "../wren-types" }

[dev-dependencies]
ast-grep-core.workspace = true
ast-grep-language.workspace = true
tempfile.workspace = true
wren-types = { version = "0.1.0", path = "../wren-types", features = ["test-support"] }

[lints]
workspace = true
