[package]
name = "wren-position"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
wren-text = { version = "0.1.0", path = "../wren-text" }
wren-types = { version = "0.1.0", path = "../wren-types" }

[dev-dependencies]
wren-types = { version = "0.1.0", path = "../wren-types", features = ["test-support"] }

[lints]
workspace = true
