[package]
name = "wren-shmem"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
benchmarking = ["wren-types/benchmarking"]

[dependencies]
mmap-io.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
wren-types = { version = "0.1.0", path = "../wren-types" }

[dev-dependencies]
tempfile.workspace = true
wren-types = { version = "0.1.0", path = "../wren-types", features = ["benchmarking"] }

[lints]
workspace = true
