[package]
name = "wren-corpus"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
wren-text = { version = "0.1.0", path = "../../crates/wren-text", features = ["benchmarking"] }
wren-types = { version = "0.1.0", path = "../../crates/wren-types" }
wren-benchmark-support = { version = "0.1.0", path = "../benchmark-support" }

[lints]
workspace = true
