[package]
name = "wren-proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true
thiserror.workspace = true
wren-types = { version = "0.1.0", path = "../wren-types" }

[build-dependencies]
prost-build = "0.14.4"
protox = "0.9.1"

[lints]
workspace = true
