[package]
name = "wren-provider"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wren-client-providers"
path = "src/main.rs"

[features]
default = ["gpu"]
gpu = ["dep:pollster", "dep:wgpu"]

[dependencies]
ast-grep-core.workspace = true
ast-grep-language.workspace = true
nucleo-matcher.workspace = true
regex.workspace = true
tree-sitter.workspace = true
pollster = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
wgpu = { workspace = true, optional = true }
wren-types = { version = "0.1.0", path = "../wren-types" }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "provider_acceleration"
harness = false
required-features = ["gpu"]

[lints]
workspace = true
